### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by obweix** [mxdldev/android-mvp-mvvm-flytour#12]
同步时提示CONFIGURE SUCCESSFUL in 0s，但没有debug configulations生成。提示Gradle project sync failed。

环境：
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0

**Comment by 994108345** [comment]
您好，我最近比较忙，我会尽快给你回复。

**Comment by liumw-git** [comment]
您好，您的邮件已收到，我会尽快拜读，谢谢！

**Comment by obweix** [comment]
是android studio版本的问题，换成旧版本就好了

**Comment by 994108345** [comment]
您好，我最近比较忙，我会尽快给你回复。

**Comment by liumw-git** [comment]
您好，您的邮件已收到，我会尽快拜读，谢谢！
